GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_LI_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_RQ_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_RS_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_STDRA_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_STDRH_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_SRLOA_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_SRLO_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_LOQ_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_LOS_VW TO [SMUSTF\HENDRYW]
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SIS_IC_LO_VW TO [SMUSTF\HENDRYW]

GO